travis:
  secure:
    BINSTAR_TOKEN: aOrrELnYF87lFipPDUCLJTC2JTnS390tZ19NUi6QEYfk9sQJEcGBPetIHKp/wdlJ8kxmqd6rAui5DRbT4kER1s84LFkEIQK6nEz7y/E0ZHXJdQCXtLh3+Hi5sW0W6X0AyiIa7rMmexCNvCDK7+Vq4DTY++DmCflM4U7/ukVv8sbONb1r8rZjJ3hHFjno+kcZVOs6jwIBDeI470zDsElT6DVWH0n43StsRN+5+hVacbWhhHy1O4mCuww+OoVnyfIGqjMUYADgxszMM/Shi0P8BZnxT3KSSw8r0+qHzJITjEM+w0l6OT21Y+nlaed6i2bsjt1um539noyAf0nZ1BhJ5SNJqUgnx+npp3hNz6HhyRhXDDePeuw6fSqXgOxkpsLlifAk2iR2rPpFuPGq+w4UkZdJ37/8C8EOiV6OjSUifxTHeNtMRbjwyNJk/jGA0z0CMr6l0WAOq/r4nsBCKs+0XvzdCzpdHbAFLziYy+8GeBb8TnET9C9uBOYNHas7rssP2OWL3ptK0fNwl3ZUB/D9OTTSMgn/TjOm+JfLjEB9CEYevnUebNAXIQgR0/KZe3wqki60FjE5e77Meq3TCid2JOzm8dsdFOKOfpZ7gVF4dkEdD4aTPKp93/e9+mK0JDK2RuFgl0Eb28c87AJe+1MzliELVb5Ynx9iSft+frvkDIE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
