travis:
  secure:
    BINSTAR_TOKEN: a7QBRS5U13dRZX6aQ9US0JtjyFUWx/0OLmf0etC7ffabXzECBuxXf+zvdZw0TEd8ekc3W2WsVroaObt3I5V4PdK4LExOhsS3Qm2gX9uLZ7pnBbSXt2ITPdzjfJFgTNlLapa6XEGMOsnBlsMSlF5bb0SaCF0GNOTFb3qqkriZ+oJDo2EvzxKZIS8BGTitnFKdOtVwAqvKnhNVDm0oxaXqCVFby/9/JImm6Fiml1duUDDQB4BKJoroGhec/WFt7gShqsMU/a6MsyJfsTUC5IUQaN68NkBXf9Qw7xqw2KNCOw4ZuisstFyvE8vLIW4zNycTTbl6T0Uy9cqMotNIKVmWEbCrHZ6O7nM+ltDGeIcu81sKUCGzyrqbgp52yaz3bltLkr3J/2jvpJLZEpdw+8LAmI0tsOLWVfFclAHemKh+Nm61N6Km/luSFuMDX82Zz73xJ0Q/4fWdPN7tMDY3s1FzIvyMmdU3UHNn6MT+30a3ra7eAJQ5WlWQOMvovc7QZ6F0gBdJ+VC+IOWaYS5KJDCir4VGqqrN+aVuvQTakMNnBYg+u4mfMnebpJ9xihCUWyzTKaN1IgyJpQx6y35JDuLqZLwgkhzzt7Ej0+WGrs4UCUSB2womBl415B2G5+EyQJbz27oNDiZg/ZP+WXo/Kf+hbvynLLLNtC7ID16bsrsP/nY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
