travis:
  secure:
    BINSTAR_TOKEN: Dj+8YTfGYxdg0rySPsv7ZBPCy0av3ifF0Yuupyekojlnu42RyQb4fRETHCD+1Qzh2hN+DJM2GDH7K8jfgx1z32PnDDGw6rh4dYuYdwLbxQvAj/gxkui9i56yCkDtpHc/HDY71zlWhZTpmwq2vCeSMTes5Xb+64ZE34L+NVxake4kpmeUpbBvbGsuqq+hdHW1qsOi8TfHI4FqdYbQygrF2Jnn6CVotmv/zDsIgLO264sYP3HRhQEDFpjkdPLJSOY4S+M0+5I17j9Wqn6WuMwsr1s+rbH1khHqV+JN31OTmacMopU64GHs4BFAoRP/kraqcPCN31cDUAEyUjKQNJcB1CixNEuhrLFSeqHL7jSMlh9uVNJLxUS1F18m5clmvKhamSzAH7JXTFMPLS4fZKtAMfpe5twnfZCgk/pqVovVWZPUulQQXAacS73t0kFnClw1mWwn59N5cQcVEcVb62I+1HlHYDNSc41js39HrjHgXThKnxL08JbS6LdBqy+59FZ19QW8zKoLPFD/Lpy7hjz4IUOUUoGNzT4i00IBU/7WiSK5227xISidLEWwLjDr9YVjDruQxG6NephgANlA00H492AM3x8UFc79/kOdwg+hZ9WuxoRXncE/rlAHMB2YtPNJarfP44TNj9r75hFnMgikiXDVjlak8G2lNMrrzrWWcEA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
