travis:
  secure:
    BINSTAR_TOKEN: bzleVVMcqHiLD1KjaIGNIHFmamXJsXoLqeHUp83LwsnsGEyyfMkmABJX33dH3dcgpFldb3GHS5jK5geRKbU4OIIcG2RRUpJvFnd1wNH1Qev5/zZpl6NPdlnaYbPoie/w/xVMDmrEtDtYR9ArUy3kHy/yOT9lL8MNhrdVSPm7gKrn0ApHhbWEf7bCTVwk04fWF9NDXwD0razLMwMU+VogeOWOEPBXdTFLt22jTr57N2vUGn4sWUgUtcSvddqwT33v6qdyA/RAidrmZTrd+6c7V6Rl7fSh4pC+1ECJ0/mTbJY2nfKk1uJKFnN1g2CHiow9xPU9EtoCXJJXGAJRgw/m2vfQfQ82IKRqQ/VwCeb4eAujwQz3uoUURHVKj7deQKAgpSwEY3QwhU229e/Qqwnp+qAWo2Is7lrY3F5X/+8n0AyQLpA4U6T7tI61nRbyZM1drmv6bmXWcJCm4JrheILOnemO2iJfRo4EAIRbqGDaYjb6+S80N4xeW997GAMfBxrDXm4LGub5NLA5UzxMxACZyzXuJdfhnUMl6G6bcS33uI/hoO5GlQsE+IX7oEI8XH+gq5YXP8cDbVGz7sTQdhfSvClsTXO3MnoPTEgJUQ+v9yWkpYdCqOlJqxnxjT+Qfxq1AZnTNT9/3gRw5nQkQn1uYi7L3fmtMBjT/d3SvQujmBE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
