travis:
  secure:
    BINSTAR_TOKEN: bSh3nYw/7lnefp5qb/VTrC6sk5KBB7GUbfEbPnH1YNRWVabg8O4qfJJ1gUhx2ODHFJiGKOCcP5EMnAhKeLapoSTMoDlaqf5f2fc3hRRyC/jEBW6jLg1aBf6jyfievUxt7aHoZv2kWB7q7dXqmPqycRRfmKLFizc/7AAin614XO2T1K5zUj7m11USNWzxCfHVWHU9c7JgJQM3t0eimlW5kuC/ds+d6OP1yeInsRsvIG25qssL5gPyMv5wr30kgMTyuMVgl713Sr73DqvZtqhkUUK2jAGRC5ZLya9mbUC/MgNcIQj+BVtWHQP3lnr5jk1qtRGCj+pSzBlgt7cASp9GhGaDv2Km+lrBLK2Dm3IMs0pWr5IC5MSUi+pjUmRvy8b0jPD+Zq7z3gLuogY+IXqHMIS7oZDdg6xOydn0/6JtvYXN3gk/BkMQmHTwrszvMfOhTInEp7zG4pYX4LTsrPxcfBQhBIg3j1rVpDEDD2a51a2KiH+ABygPAQ87ySJoBTKwlnCUmf/dr2gfZPkONvWZNI0tJZUvaigWEloOLhAtpPTxDdZwvOE7FkmyhcE2eCaM27FfqHEOHIo865VsEtuqAChIw5z4bn/VBkZzM1gMDJamqJ8WewVJr+zugROstqmNynmI1prGGVGZXGYd1GM26L6t4LrkL/7yZftCwhIcxsU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
